apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: observiq-logs

secretGenerator:  
- name: observiq-agent-secrets
  envs:
  - oiq.env

resources:
  - git::http://github.com/ssmiller25/blast-apps/observiq-logs?ref=main